// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtryriYU2rp6_pnOR0xf6LAkDxjRYYkDg',
    appId: '1:157056108960:web:6129e766f28e7837cdbcc5',
    messagingSenderId: '157056108960',
    projectId: 'shivik-5c975',
    authDomain: 'shivik-5c975.firebaseapp.com',
    storageBucket: 'shivik-5c975.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK1lNw1hGJIhoqrsYWtEi3MIaH-jCcxcU',
    appId: '1:157056108960:android:eb6da525039dffe0cdbcc5',
    messagingSenderId: '157056108960',
    projectId: 'shivik-5c975',
    storageBucket: 'shivik-5c975.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8j1Wv3h0b7b-zX7Db8tfyk3xE-pqULxM',
    appId: '1:157056108960:ios:7be58cbf80a351d7cdbcc5',
    messagingSenderId: '157056108960',
    projectId: 'shivik-5c975',
    storageBucket: 'shivik-5c975.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8j1Wv3h0b7b-zX7Db8tfyk3xE-pqULxM',
    appId: '1:157056108960:ios:7be58cbf80a351d7cdbcc5',
    messagingSenderId: '157056108960',
    projectId: 'shivik-5c975',
    storageBucket: 'shivik-5c975.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtryriYU2rp6_pnOR0xf6LAkDxjRYYkDg',
    appId: '1:157056108960:web:b0cb9af5cba50613cdbcc5',
    messagingSenderId: '157056108960',
    projectId: 'shivik-5c975',
    authDomain: 'shivik-5c975.firebaseapp.com',
    storageBucket: 'shivik-5c975.firebasestorage.app',
  );
}
